### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by GoingMyWay** [chawuchen/Wildscav_fps_mcc_fang#1]
Dear authors,

Did you write a paper to introduce methods you used in this repo?

Thank you!

**Comment by chawuchen** [comment]
Actually I'm currently writing this paper, and I plan to submit it this month. The code here is not the latest. I may update later.

**Comment by GoingMyWay** [comment]
> Actually I'm currently writing this paper, and I plan to submit it this month. The code here is not the latest. I may update later.

Great! Thanks for the prompt response. Kindly let me know when the paper is available.
